apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  generation: 1
  name: put-to-topic
  selfLink: /apis/camel.apache.org/v1/namespaces/fruit-stand/integrations/put-to-topic
spec:
  sources:
  - content: |
      // camel-k: language=java
      import org.apache.camel.builder.RouteBuilder;

      public class PutToTopic extends RouteBuilder {
        @Override
        public void configure() throws Exception {

            // Write your routes here, for example:
            from("timer://foo?repeatCount=1")
              .setBody()
                .simple("WHATEVER??")
              .to("kafka:producer?brokers=my-cluster-kafka-bootstrap:9092");
        }
      }
    name: PutToTopic.java
